apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "th.co.central.ris.bootlauncher"
        minSdkVersion 19
        targetSdkVersion 19
        versionCode 31
        versionName "5.0"
    }

    buildTypes {
        release { minifyEnabled false }
        debug { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {}
